name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build_apk:
    runs-on: ubuntu-latest
    container: kivy/buildozer

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build APK
        run: |
          # This picks up buildozer.spec from repo root
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: pd-game-apk
          path: bin/*.apk
